# Generated by Django 5.1.4 on 2024-12-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='design_choice',
            field=models.CharField(choices=[('design1', 'Design 1'), ('design2', 'Design 2')], default='design1', max_length=10),
        ),
    ]
