# Generated by Django 5.1.4 on 2024-12-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_category_design_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_choice',
            field=models.CharField(choices=[('food', 'Food'), ('drink', 'Drink')], default='drink', max_length=10),
        ),
    ]
